language: c 
os:
   - linux
   - osx

compiler:
  - clang
  - gcc

before_script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq tcl8.5; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ] ; then brew update; brew tap homebrew/dupes; brew install tcl-tk;fi script:
  - make
  
